export default {
    GET_USER_DATA: 'GET_USER_DATA',
    USER_LOGIN: 'USER_LOGIN',
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGOUT: 'USER_LOGOUT',
    INIT_FORM: 'INIT_FORM',
    CLEAR_FORM: 'CLEAR_FORM',
    SET_FORM_ERRORS: 'SET_FORM_ERRORS',
    CLEAR_FORM_ERRORS: 'CLEAR_FORM_ERRORS',
    UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD',
    UPDATE_FORM_FIELDS: 'UPDATE_FORM_FIELDS'
}
